"""
Seed the database with a curated collection of popular movies.
Run once: python seed.py
"""

import os
from dotenv import load_dotenv
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
load_dotenv(BASE_DIR / ".env")

from database import get_db, get_next_id
from recommendation import build_recommendation_model

# Curated movie dataset - 60 popular movies with real data
MOVIES_DATA = [
    {"tmdb_id": 693134, "title": "Dune: Part Two", "genre": "Science Fiction, Adventure", "overview": "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.", "rating": 8.2, "release_date": "2024-02-27", "poster_path": "/8b8R8l88Qje9dn9OE8PY05Nez7.jpg", "backdrop_path": "/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg", "popularity": 2500.0, "vote_count": 5200},
    {"tmdb_id": 157336, "title": "Interstellar", "genre": "Adventure, Drama, Science Fiction", "overview": "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.", "rating": 8.7, "release_date": "2014-11-05", "poster_path": "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg", "backdrop_path": "/xJHokMbljvjADYdit5fK1Deo1vx.jpg", "popularity": 1800.0, "vote_count": 32000},
    {"tmdb_id": 27205, "title": "Inception", "genre": "Action, Science Fiction, Adventure", "overview": "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: inception.", "rating": 8.4, "release_date": "2010-07-15", "poster_path": "/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg", "backdrop_path": "/s3TBrRGB1iav7gFOCNx3H31MoES.jpg", "popularity": 1500.0, "vote_count": 35000},
    {"tmdb_id": 49026, "title": "The Dark Knight Rises", "genre": "Action, Crime, Drama, Thriller", "overview": "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late combating organized crime.", "rating": 7.8, "release_date": "2012-07-16", "poster_path": "/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg", "backdrop_path": "/f6ljQGv7WnJuwBPty017aq6pQ98.jpg", "popularity": 1200.0, "vote_count": 20000},
    {"tmdb_id": 155, "title": "The Dark Knight", "genre": "Drama, Action, Crime, Thriller", "overview": "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets.", "rating": 9.0, "release_date": "2008-07-16", "poster_path": "/qJ2tW6WMUDux911BtREEMo8pmyv.jpg", "backdrop_path": "/nMKdUUepR0i5zn0y1T4CsSB5ez.jpg", "popularity": 1400.0, "vote_count": 30000},
    {"tmdb_id": 872585, "title": "Oppenheimer", "genre": "Drama, History", "overview": "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.", "rating": 8.1, "release_date": "2023-07-19", "poster_path": "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg", "backdrop_path": "/nb3xI8XI3w4pMVZ38VijbsyBqP4.jpg", "popularity": 2300.0, "vote_count": 8000},
    {"tmdb_id": 346698, "title": "Barbie", "genre": "Comedy, Adventure, Fantasy", "overview": "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.", "rating": 7.0, "release_date": "2023-07-19", "poster_path": "/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg", "backdrop_path": "/nHf61UzkfFno5dCRe3c0x5JFv6B.jpg", "popularity": 2100.0, "vote_count": 7500},
    {"tmdb_id": 569094, "title": "Spider-Man: Across the Spider-Verse", "genre": "Animation, Action, Adventure", "overview": "After reuniting with Gwen Stacy, Brooklyn's full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society.", "rating": 8.4, "release_date": "2023-05-31", "poster_path": "/8Vt6mWEReuy5Of61Lnj5Xj704m8.jpg", "backdrop_path": "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg", "popularity": 1900.0, "vote_count": 6000},
    {"tmdb_id": 614930, "title": "Teenage Mutant Ninja Turtles: Mutant Mayhem", "genre": "Animation, Action, Comedy", "overview": "After years of being sheltered from the human world, the Turtle brothers set out to win the hearts of New Yorkers and be accepted as normal teenagers through heroic acts.", "rating": 7.3, "release_date": "2023-07-31", "poster_path": "/ueO9MYIOHO7M1PiMUeX74uf8fB9.jpg", "backdrop_path": "/deLWkOLZmBNkm8p16igfapQyqeq.jpg", "popularity": 900.0, "vote_count": 2500},
    {"tmdb_id": 550, "title": "Fight Club", "genre": "Drama, Thriller, Comedy", "overview": "A ticking-Loss, insomnia-Loss insurance worker and a devil-may-care soapmaker form an underground fist-fighting club that evolves into something much, much more.", "rating": 8.4, "release_date": "1999-10-15", "poster_path": "/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg", "backdrop_path": "/hZkgoQYus5dXo3H8T7Uef6DNknx.jpg", "popularity": 1600.0, "vote_count": 27000},
    {"tmdb_id": 238, "title": "The Godfather", "genre": "Drama, Crime", "overview": "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael, steps in.", "rating": 8.7, "release_date": "1972-03-14", "poster_path": "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg", "backdrop_path": "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg", "popularity": 1300.0, "vote_count": 19000},
    {"tmdb_id": 680, "title": "Pulp Fiction", "genre": "Thriller, Crime", "overview": "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper.", "rating": 8.5, "release_date": "1994-09-10", "poster_path": "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg", "backdrop_path": "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg", "popularity": 1400.0, "vote_count": 26000},
    {"tmdb_id": 278, "title": "The Shawshank Redemption", "genre": "Drama, Crime", "overview": "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work.", "rating": 8.7, "release_date": "1994-09-23", "poster_path": "/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg", "backdrop_path": "/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg", "popularity": 1200.0, "vote_count": 24000},
    {"tmdb_id": 13, "title": "Forrest Gump", "genre": "Comedy, Drama, Romance", "overview": "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do.", "rating": 8.5, "release_date": "1994-06-23", "poster_path": "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg", "backdrop_path": "/7c9UVPPiTPltouxRVY6N9uugaVA.jpg", "popularity": 1100.0, "vote_count": 25000},
    {"tmdb_id": 603, "title": "The Matrix", "genre": "Action, Science Fiction", "overview": "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.", "rating": 8.2, "release_date": "1999-03-30", "poster_path": "/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg", "backdrop_path": "/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg", "popularity": 1300.0, "vote_count": 24000},
    {"tmdb_id": 120, "title": "The Lord of the Rings: The Fellowship of the Ring", "genre": "Adventure, Fantasy, Action", "overview": "Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator.", "rating": 8.4, "release_date": "2001-12-18", "poster_path": "/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg", "backdrop_path": "/pIUvQ9Ed35wlWhY2oU6OmwEgzjh.jpg", "popularity": 1100.0, "vote_count": 23000},
    {"tmdb_id": 122, "title": "The Lord of the Rings: The Return of the King", "genre": "Adventure, Fantasy, Action", "overview": "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces.", "rating": 8.5, "release_date": "2003-12-01", "poster_path": "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg", "backdrop_path": "/pm0RiwNpSja8gR0BTWpxo5a9Bbl.jpg", "popularity": 1000.0, "vote_count": 22000},
    {"tmdb_id": 438631, "title": "Dune", "genre": "Science Fiction, Adventure", "overview": "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people.", "rating": 7.8, "release_date": "2021-09-15", "poster_path": "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg", "backdrop_path": "/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg", "popularity": 1600.0, "vote_count": 10000},
    {"tmdb_id": 299536, "title": "Avengers: Infinity War", "genre": "Adventure, Action, Science Fiction", "overview": "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos.", "rating": 8.3, "release_date": "2018-04-25", "poster_path": "/7WsyChQLEftFiDhRkZnR46wP27.jpg", "backdrop_path": "/bOGkgRGdhrBYJSLpXaxhXVstddV.jpg", "popularity": 1500.0, "vote_count": 26000},
    {"tmdb_id": 299534, "title": "Avengers: Endgame", "genre": "Adventure, Science Fiction, Action", "overview": "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance.", "rating": 8.3, "release_date": "2019-04-24", "poster_path": "/or06FN3Dka5tukK1e9GladR3Eey.jpg", "backdrop_path": "/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg", "popularity": 1500.0, "vote_count": 23000},
    {"tmdb_id": 19995, "title": "Avatar", "genre": "Action, Adventure, Fantasy, Science Fiction", "overview": "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.", "rating": 7.6, "release_date": "2009-12-15", "poster_path": "/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg", "backdrop_path": "/o0s4XsEDfDlvit5pDRKjzXR4pp2.jpg", "popularity": 1200.0, "vote_count": 28000},
    {"tmdb_id": 76600, "title": "Avatar: The Way of Water", "genre": "Science Fiction, Adventure, Action", "overview": "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe.", "rating": 7.6, "release_date": "2022-12-14", "poster_path": "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg", "backdrop_path": "/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg", "popularity": 1400.0, "vote_count": 11000},
    {"tmdb_id": 505642, "title": "Black Panther: Wakanda Forever", "genre": "Action, Adventure, Science Fiction, Drama", "overview": "Queen Ramonda, Shuri, M'Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T'Challa's death.", "rating": 7.3, "release_date": "2022-11-09", "poster_path": "/sv1xJUazXeYqALzczSZ3O6nkH75.jpg", "backdrop_path": "/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg", "popularity": 800.0, "vote_count": 5000},
    {"tmdb_id": 572802, "title": "Aquaman and the Lost Kingdom", "genre": "Action, Adventure, Fantasy", "overview": "Black Manta seeks revenge on Aquaman. With the power of the Black Trident that corrupts all it touches, Aquaman must turn to his imprisoned brother Orm to stop Black Manta.", "rating": 6.5, "release_date": "2023-12-20", "poster_path": "/7lTnXOy0iNtBAdRP3TZvaKJ77F6.jpg", "backdrop_path": "/7lTnXOy0iNtBAdRP3TZvaKJ77F6.jpg", "popularity": 700.0, "vote_count": 3000},
    {"tmdb_id": 466420, "title": "Killers of the Flower Moon", "genre": "Crime, Drama, History", "overview": "When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one—until the FBI steps in to unravel the mystery.", "rating": 7.5, "release_date": "2023-10-18", "poster_path": "/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg", "backdrop_path": "/1X7vow16X7CnCoexXh4H4F2yDJv.jpg", "popularity": 1100.0, "vote_count": 4000},
    {"tmdb_id": 792307, "title": "Poor Things", "genre": "Science Fiction, Romance, Comedy", "overview": "Brought back to life by an unorthodox scientist, a young woman runs off with a lawyer on a whirlwind adventure across the continents pursuing liberation and experience.", "rating": 7.8, "release_date": "2023-12-07", "poster_path": "/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg", "backdrop_path": "/bQS43HSLZzMjZkcHJz4fGc7fNdz.jpg", "popularity": 1000.0, "vote_count": 3500},
    {"tmdb_id": 496243, "title": "Parasite", "genre": "Comedy, Thriller, Drama", "overview": "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.", "rating": 8.5, "release_date": "2019-05-30", "poster_path": "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg", "backdrop_path": "/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg", "popularity": 900.0, "vote_count": 16000},
    {"tmdb_id": 786892, "title": "Furiosa: A Mad Max Saga", "genre": "Action, Adventure, Science Fiction", "overview": "As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great Biker Horde led by the Warlord Dementus.", "rating": 7.6, "release_date": "2024-05-22", "poster_path": "/iADOJ8Zymht2JPMoy3R7xceZprc.jpg", "backdrop_path": "/wNAhuOZ3Zf84jCIlrcI6JhgmY5.jpg", "popularity": 1800.0, "vote_count": 4500},
    {"tmdb_id": 823464, "title": "Godzilla x Kong: The New Empire", "genre": "Science Fiction, Action, Adventure", "overview": "Following their fruit battle against Mechagodzilla, Godzilla and Kong face a mysterious colossal undiscovered threat hidden within our world.", "rating": 7.1, "release_date": "2024-03-27", "poster_path": "/z1p34vh7dEOnLDV4jC10KcjaLRq.jpg", "backdrop_path": "/veIyxxi5Gs8gvztLEW1Ysb8rrzs.jpg", "popularity": 2000.0, "vote_count": 3000},
    {"tmdb_id": 653346, "title": "Kingdom of the Planet of the Apes", "genre": "Science Fiction, Adventure, Action", "overview": "Several generations in the future following Caesar's reign, apes are the dominant species and live harmoniously while humans have been reduced to living in the shadows.", "rating": 7.1, "release_date": "2024-05-08", "poster_path": "/gKkl37BQuKTanygYQG1pyYgLVgf.jpg", "backdrop_path": "/fqv8v6AycXKsivp1T5yKtLbGXce.jpg", "popularity": 1700.0, "vote_count": 2500},
    {"tmdb_id": 1011985, "title": "Kung Fu Panda 4", "genre": "Animation, Action, Family, Comedy", "overview": "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior.", "rating": 7.1, "release_date": "2024-03-02", "poster_path": "/kDp1vUBnMpe8ak4rjgl3cLELqJU.jpg", "backdrop_path": "/1XDDXPXGiI8id7MrUxK36be7Mvo.jpg", "popularity": 1600.0, "vote_count": 2800},
    {"tmdb_id": 634649, "title": "Spider-Man: No Way Home", "genre": "Action, Adventure, Science Fiction", "overview": "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous.", "rating": 8.0, "release_date": "2021-12-15", "poster_path": "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg", "backdrop_path": "/iQFcwSGbZXMk2MKbOGl6PgKNi.jpg", "popularity": 1400.0, "vote_count": 18000},
    {"tmdb_id": 385687, "title": "Fast X", "genre": "Action, Crime, Thriller", "overview": "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path.", "rating": 7.0, "release_date": "2023-05-17", "poster_path": "/fiVW06jE7z9YnO4trhaMEdclSiC.jpg", "backdrop_path": "/4XM8DUN5lhps0r7BL96CabrMmTb.jpg", "popularity": 1200.0, "vote_count": 5500},
    {"tmdb_id": 575264, "title": "Mission: Impossible - Dead Reckoning Part One", "genre": "Action, Thriller", "overview": "Ethan Hunt and his IMF team embark on their most dangerous mission yet: To track down a terrifying new weapon that threatens all of humanity.", "rating": 7.6, "release_date": "2023-07-08", "poster_path": "/NNxYkU70HPurnNCSiCjYAmacwm.jpg", "backdrop_path": "/628Dep6AxEtDxjZoGP78TsOxYbK.jpg", "popularity": 1000.0, "vote_count": 4000},
    {"tmdb_id": 940551, "title": "Migration", "genre": "Animation, Family, Adventure, Comedy", "overview": "After a family of ducks decides to leave New England, their routine life, and fly to Jamaica for the winter, things quickly go sideways.", "rating": 7.4, "release_date": "2023-12-06", "poster_path": "/ldfCF9RhR40l29Vnzhx9kC7DGG.jpg", "backdrop_path": "/2KGxQFV9Wp1MshPBf8BuqWUgNAB.jpg", "popularity": 800.0, "vote_count": 2000},
    {"tmdb_id": 787699, "title": "Wonka", "genre": "Comedy, Family, Fantasy", "overview": "Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream.", "rating": 7.2, "release_date": "2023-12-06", "poster_path": "/qhb1qOilapbapxWQn9jtRCMwXJF.jpg", "backdrop_path": "/yOm993lsJyPmBodlYjgpPwBjXP9.jpg", "popularity": 900.0, "vote_count": 3000},
    {"tmdb_id": 609681, "title": "Napoleon", "genre": "History, War, Drama", "overview": "An epic that details the checkered rise and fall of French Emperor Napoleon Bonaparte and his relentless journey to power through the prism of his addictive, volatile relationship with his wife.", "rating": 6.5, "release_date": "2023-11-22", "poster_path": "/jE5skGBv0UGiXcFsDq5NY19sNEd.jpg", "backdrop_path": "/dZbLqRjjiiNCpSfGz8FnvSk6FnM.jpg", "popularity": 800.0, "vote_count": 3500},
    {"tmdb_id": 792293, "title": "Ferrari", "genre": "Drama, History", "overview": "Set during the summer of 1957, the film follows Enzo Ferrari as his auto empire faces bankruptcy and the dangerous Mille Miglia race across Italy.", "rating": 6.5, "release_date": "2023-12-25", "poster_path": "/r1zCU1qHx9sizU8iBNPOmmpHQC.jpg", "backdrop_path": "/lmLfr0bTn3ro7P0dN7RLjLsoBYU.jpg", "popularity": 700.0, "vote_count": 2000},
    {"tmdb_id": 1022789, "title": "Inside Out 2", "genre": "Animation, Family, Adventure, Comedy", "overview": "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust are not sure how to feel when Anxiety shows up.", "rating": 7.6, "release_date": "2024-06-11", "poster_path": "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg", "backdrop_path": "/xg27NrXi7VXCGUr7MN75UqLl6Vg.jpg", "popularity": 2200.0, "vote_count": 6000},
    {"tmdb_id": 929590, "title": "Civil War", "genre": "War, Action, Drama", "overview": "In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.", "rating": 7.0, "release_date": "2024-04-10", "poster_path": "/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg", "backdrop_path": "/z121dSTR7PY9KxKuvwiIFSYW8cf.jpg", "popularity": 1500.0, "vote_count": 3200},
    {"tmdb_id": 438148, "title": "Minions: The Rise of Gru", "genre": "Animation, Family, Comedy, Adventure", "overview": "A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enough to join them.", "rating": 7.1, "release_date": "2022-06-29", "poster_path": "/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg", "backdrop_path": "/rC3dY2sEBClkPfjrW42IB6RqxIO.jpg", "popularity": 700.0, "vote_count": 4500},
    {"tmdb_id": 315162, "title": "Puss in Boots: The Last Wish", "genre": "Animation, Action, Adventure, Comedy, Family, Fantasy", "overview": "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left.", "rating": 8.3, "release_date": "2022-12-07", "poster_path": "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg", "backdrop_path": "/r9PkFnRUIthgBp2JZZzD380MWZy.jpg", "popularity": 900.0, "vote_count": 7000},
    {"tmdb_id": 447277, "title": "The Little Mermaid", "genre": "Adventure, Family, Fantasy, Romance", "overview": "The youngest of King Triton's daughters, and the most defiant, Ariel longs to find out more about the world beyond the sea, and while visiting the surface, falls for the dashing Prince Eric.", "rating": 6.5, "release_date": "2023-05-18", "poster_path": "/ym1dxyOk4jFcSl4Q2zmRrA5LQLP.jpg", "backdrop_path": "/j1F2Iz7cRgFSPN4xbB1ogRyrkHd.jpg", "popularity": 600.0, "vote_count": 3500},
    {"tmdb_id": 447365, "title": "Guardians of the Galaxy Vol. 3", "genre": "Science Fiction, Adventure, Action", "overview": "Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own.", "rating": 8.0, "release_date": "2023-05-03", "poster_path": "/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg", "backdrop_path": "/5YNMsmAY7jDoZn2ErlbaHm0R3RI.jpg", "popularity": 1000.0, "vote_count": 6000},
    {"tmdb_id": 667538, "title": "Transformers: Rise of the Beasts", "genre": "Action, Adventure, Science Fiction", "overview": "When a new threat capable of destroying the entire planet emerges, Optimus Prime and the Autobots must team up with a powerful faction known as the Maximals.", "rating": 7.2, "release_date": "2023-06-06", "poster_path": "/gPbM0MK8CP8A174rmUwGsADRChI.jpg", "backdrop_path": "/bz66a19bR6BKsbY8gSZCM4etJiK.jpg", "popularity": 800.0, "vote_count": 4500},
    {"tmdb_id": 76341, "title": "Mad Max: Fury Road", "genre": "Action, Adventure, Science Fiction", "overview": "An apocalyptic story set in the furthest reaches of our planet, in a stark desert landscape where humanity is broken.", "rating": 7.6, "release_date": "2015-05-13", "poster_path": "/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg", "backdrop_path": "/phszHPFVhPHhMZgo0fWTKBDQsJA.jpg", "popularity": 1000.0, "vote_count": 20000},
    {"tmdb_id": 68718, "title": "Django Unchained", "genre": "Drama, Western", "overview": "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.", "rating": 8.2, "release_date": "2012-12-25", "poster_path": "/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg", "backdrop_path": "/2oZklIzUbvZXXzIFzv7Hi68d6xf.jpg", "popularity": 1100.0, "vote_count": 25000},
    {"tmdb_id": 24428, "title": "The Avengers", "genre": "Science Fiction, Action, Adventure", "overview": "When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as SHIELD, needs a team.", "rating": 7.7, "release_date": "2012-04-25", "poster_path": "/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg", "backdrop_path": "/kwUQFeFXOOpgloMgZaadhzkbCMh.jpg", "popularity": 1000.0, "vote_count": 29000},
    {"tmdb_id": 533535, "title": "Deadpool & Wolverine", "genre": "Action, Comedy, Science Fiction", "overview": "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must suit up again.", "rating": 7.7, "release_date": "2024-07-24", "poster_path": "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg", "backdrop_path": "/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg", "popularity": 2400.0, "vote_count": 7000},
    {"tmdb_id": 671, "title": "Harry Potter and the Philosopher's Stone", "genre": "Adventure, Fantasy", "overview": "Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard.", "rating": 7.9, "release_date": "2001-11-16", "poster_path": "/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg", "backdrop_path": "/hziiv14OpD73u9gAak4XDDfBKa2.jpg", "popularity": 900.0, "vote_count": 25000},
    {"tmdb_id": 11, "title": "Star Wars", "genre": "Adventure, Action, Science Fiction", "overview": "Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.", "rating": 8.2, "release_date": "1977-05-25", "poster_path": "/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg", "backdrop_path": "/zqkmTXzjkAgXmEWLRsY4UpTWCeo.jpg", "popularity": 900.0, "vote_count": 19000},
    {"tmdb_id": 934632, "title": "The Marvels", "genre": "Action, Adventure, Science Fiction", "overview": "Carol Danvers, aka Captain Marvel, has reclaimed her identity from the tyrannical Kree and taken revenge on the Supreme Intelligence. But unintended consequences see Carol shouldering the burden of a destabilized universe.", "rating": 6.3, "release_date": "2023-11-10", "poster_path": "/9GBhzXMFjgcZ3FdR9w3bUMMOps.jpg", "backdrop_path": "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg", "popularity": 700.0, "vote_count": 3500},
    {"tmdb_id": 580489, "title": "Venom: Let There Be Carnage", "genre": "Science Fiction, Action, Adventure", "overview": "After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.", "rating": 7.0, "release_date": "2021-09-30", "poster_path": "/rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg", "backdrop_path": "/eENEf_r9ggSchwBwqaFqn8T5nFr.jpg", "popularity": 600.0, "vote_count": 8000},
    {"tmdb_id": 502356, "title": "The Super Mario Bros. Movie", "genre": "Animation, Adventure, Family, Fantasy, Comedy", "overview": "While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world.", "rating": 7.7, "release_date": "2023-04-05", "poster_path": "/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg", "backdrop_path": "/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg", "popularity": 1000.0, "vote_count": 8000},
    {"tmdb_id": 956372, "title": "The Holdovers", "genre": "Comedy, Drama", "overview": "A curmudgeonly instructor at a New England prep school is forced to remain on campus during Christmas break to babysit the handful of students with nowhere to go. He bonds with one particular student.", "rating": 7.7, "release_date": "2023-10-27", "poster_path": "/VHSzNBTwxV8vh7wylo7O9CLdac.jpg", "backdrop_path": "/zCK4a6L2Fy4kz3vCYUaFP4d61sI.jpg", "popularity": 600.0, "vote_count": 2500},
    {"tmdb_id": 748783, "title": "The Garfield Movie", "genre": "Animation, Family, Comedy, Adventure", "overview": "Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure!", "rating": 7.1, "release_date": "2024-04-30", "poster_path": "/p6AbOJvMQhBmffd0PIv0u8ghWeY.jpg", "backdrop_path": "/y2QB1WLIvcYG9eYCIRbej8slHny.jpg", "popularity": 1200.0, "vote_count": 2000},
    {"tmdb_id": 937278, "title": "A Quiet Place: Day One", "genre": "Horror, Science Fiction, Thriller", "overview": "As New York City is invaded by alien creatures who hunt by sound, a woman named Sam fights to survive with her cat.", "rating": 6.8, "release_date": "2024-06-26", "poster_path": "/hU42CRk14JuBxnx0sps0fVk52GI.jpg", "backdrop_path": "/8slDGkNEkLOvDSEPwBbfGdVf7RI.jpg", "popularity": 1300.0, "vote_count": 2800},
    {"tmdb_id": 150540, "title": "Inside Out", "genre": "Animation, Family, Adventure, Drama, Comedy", "overview": "Growing up can be a bumpy road, and it's no exception for Riley, who is uprooted from her Midwest life when her father starts a new job in San Francisco.", "rating": 7.9, "release_date": "2015-06-17", "poster_path": "/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg", "backdrop_path": "/j29ekbcOi8ykiDTKPwP8KyqSz2d.jpg", "popularity": 800.0, "vote_count": 20000},
    {"tmdb_id": 862, "title": "Toy Story", "genre": "Animation, Comedy, Family", "overview": "Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene.", "rating": 8.0, "release_date": "1995-10-30", "poster_path": "/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg", "backdrop_path": "/m9L5GGzCAkGQRJn9kl6cVwxY1rN.jpg", "popularity": 700.0, "vote_count": 16000},
    {"tmdb_id": 1726, "title": "Iron Man", "genre": "Action, Science Fiction, Adventure", "overview": "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.", "rating": 7.6, "release_date": "2008-04-30", "poster_path": "/78lPtwv72eTNqFW9COBYI0dWDJa.jpg", "backdrop_path": "/6YwkGolwdOMNpbTOmLjoehlVWs5.jpg", "popularity": 800.0, "vote_count": 24000},
    {"tmdb_id": 299537, "title": "Captain Marvel", "genre": "Action, Adventure, Science Fiction", "overview": "The story follows Carol Danvers as she becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war between two alien races.", "rating": 6.8, "release_date": "2019-03-06", "poster_path": "/AtsgWhDnHTq68L0jFsAbIiiNmTi.jpg", "backdrop_path": "/w2PMyoyLU22YvrGK3smVM9fW1jj.jpg", "popularity": 700.0, "vote_count": 12000},
    {"tmdb_id": 11161, "title": "Shutter Island", "genre": "Drama, Thriller, Mystery", "overview": "World War II soldier-turned U.S. Marshal Teddy Daniels investigates the disappearance of a patient from a hospital for the criminally insane, but his efforts are compromised by his own mental instability.", "rating": 8.2, "release_date": "2010-02-14", "poster_path": "/kve20tXMHZZvHIaulJMz2dAaJ8X.jpg", "backdrop_path": "/jC1KqsFx8ZyqJyQa2Ohi7xgL7XC.jpg", "popularity": 1000.0, "vote_count": 22000},
    {"tmdb_id": 475557, "title": "Joker", "genre": "Crime, Thriller, Drama", "overview": "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic criminal figure.", "rating": 8.2, "release_date": "2019-10-01", "poster_path": "/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg", "backdrop_path": "/gZWl93sf8AxavYpVT1Un6EF3oCj.jpg", "popularity": 1100.0, "vote_count": 22000},
]


def seed_database():
    """Main seeding function."""
    print("🎬 CineStream Database Seeder (MongoDB)")
    print("=" * 40)

    db = get_db()

    # Drop existing data for a clean seed
    db.movies.drop()
    db.counters.delete_one({"_id": "movies"})
    print("✅ Cleared existing movies collection")

    # Insert movies with auto-incrementing integer IDs
    inserted = 0
    for movie_data in MOVIES_DATA:
        # Check for duplicate by tmdb_id
        existing = db.movies.find_one({"tmdb_id": movie_data["tmdb_id"]})
        if existing:
            continue

        new_id = get_next_id("movies")
        doc = {
            "id": new_id,
            **movie_data,
            "user_rating_sum": 0.0,
            "user_rating_count": 0,
            "monthly_score": 0.0,
            "franchise": None,
            "wiki_summary": None,
            "wiki_plot": None,
            "wiki_cast": None,
            "wiki_director": None,
            "wiki_budget": None,
            "wiki_box_office": None,
            "wiki_runtime": None,
            "wiki_fetched": False,
        }
        db.movies.insert_one(doc)
        inserted += 1

    print(f"✅ Inserted {inserted} new movies into MongoDB")

    # Create indexes for performance
    db.movies.create_index("id", unique=True)
    db.movies.create_index("tmdb_id", unique=True)
    db.movies.create_index("title")
    db.movies.create_index([("popularity", -1)])
    db.movies.create_index([("monthly_score", -1)])
    db.movies.create_index([("rating", -1)])
    db.user_ratings.create_index([("movie_id", 1), ("user_id", 1)])
    db.comments.create_index([("movie_id", 1)])
    print("✅ Created indexes")

    # Build recommendation model
    print("\n🧠 Building recommendation model with Pickle + TF-IDF...")
    all_movies = list(db.movies.find())
    movies_for_model = [
        {
            "id": m["id"],
            "title": m["title"],
            "genre": m.get("genre", ""),
            "overview": m.get("overview", ""),
            "rating": m.get("rating", 0.0),
            "release_date": m.get("release_date"),
            "poster_path": m.get("poster_path"),
            "backdrop_path": m.get("backdrop_path"),
            "popularity": m.get("popularity", 0.0),
        }
        for m in all_movies
    ]
    build_recommendation_model(movies_for_model)

    print("\n🎉 Seeding complete! Run: uvicorn main:app --reload")


if __name__ == "__main__":
    seed_database()
